name: poc_flutter_supabase_oauth
description: "A proof of concept Flutter app integrating OAuth via Supabase."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env